### ISSUE TITLE
请教一下计算Area时出现的对负值进行开方的操作

### ISSUE THREAD

**Issue by ltCodeW** [cuge1995/curvature-calculation-python#1]
在您写得get_triangle_area函数中，当angleP0<90时，有如下的计算
`Area = (math.sqrt(R * R - p0p1 * p0p1 / 4) * p0p1) / 4 + (math.sqrt(R * R - p0p2 * p0p2 / 4) * p0p1) / 4`
R * R - p0p1 * p0p1 / 4或R * R - p0p2 * p0p2 / 4是负数时，请问area的值应该怎么定义呢？

**Comment by cuge1995** [comment]
我当时还没考虑到这个corner case哈，如果你解决了这种情况，欢迎pull request

**Comment by gitouni** [comment]
> 我当时还没考虑到这个corner case哈，如果你解决了这种情况，欢迎pull request

事实上，计算Triangle Area不需要用到角度信息，使用np.linalg.norm(np.cross(ab,bc))/2的公式即可。外积的模长就是平行四边形的面积，除以2就是三角形的面积，还可以避免角度太小造成的奇异问题。
